version: "3.8"
services:
  selenium-hub:
    image: selenium/hub:4.1.0-prerelease-20211105
    container_name: selenium-hub
    networks:
      - grid-network
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.1.0-prerelease-20211105
    shm_size: 2gb
    depends_on:
      - selenium-hub
    networks:
      - grid-network
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    deploy:
      replicas: 2

  edge:
    image: selenium/node-edge:4.1.0-prerelease-20211105
    shm_size: 2gb
    depends_on:
      - selenium-hub
    networks:
      - grid-network
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
    deploy:
      replicas: 2

  firefox:
    image: selenium/node-firefox:4.1.0-prerelease-20211105
    shm_size: 2gb
    depends_on:
      - selenium-hub
    networks:
      - grid-network
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
    deploy:
      replicas: 2

networks:
  grid-network:
    name: grid