browser: chrome

hub:
  protocol: http
  host: localhost
  port: 4444

visa:
  url: https://vins-udemy.s3.amazonaws.com/sb/visa/udemy-visa.html
  heading: VISA Registration Form
  subHeading: Fill out the form carefully for registration

flight:
  url: https://vins-udemy.s3.amazonaws.com/docker/docker-book-flight.html
  heading: Docker Flight Booking Application
  subHeading: User Registration Form

spring:
  profiles:
    active: local
  jpa:
    defer-datasource-initialization: true